region: "ap-southeast-2"
access_key: "xxxxxxxxxxxxxxxxxxxxxx"
secret_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

metrics:
  - aws_namespace: AWS/ELB
    aws_metric_name: RequestCount
    aws_dimensions: [AvailabilityZone, LoadBalancerName]
    aws_dimension_select:
      LoadBalancerName: [myLB]
    aws_statistics: [Sum]
  - aws_namespace: AWS/EC2
    aws_metric_name: CPUUtilization
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Minimum, Maximum, Sum]
    aws_unit: Percent
    aws_period: 300
  - aws_namespace: AWS/EC2
    aws_metric_name: NetworkOut
    aws_dimensions: [ InstanceId ]
    aws_statistics: [ Average, Minimum, Maximum, Sum ]
    aws_unit: Percent
    aws_period: 300
  - aws_namespace: AWS/EC2
    aws_metric_name: NetworkIn
    aws_dimensions: [ InstanceId ]
    aws_statistics: [ Average, Minimum, Maximum, Sum ]
    aws_unit: Percent
    aws_period: 300
  - aws_namespace: AWS/EC2
    aws_metric_name: MemoryUtilization
    aws_dimensions: [ InstanceId ]
    aws_statistics: [ Average, Minimum, Maximum, Sum ]
    aws_unit: Percent
    aws_period: 300
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: RequestCount
    aws_dimensions: [LoadBalancer, TargetGroup]
    aws_statistics: [Sum]
    aws_period: 300
    range_seconds: 600
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: HTTPCode_Target_5XX_Count
    aws_dimensions: [LoadBalancer, TargetGroup]
    aws_statistics: [Sum]
    aws_period: 300
    range_seconds: 600
  - aws_namespace: AWS/ApplicationELB
    aws_metric_name: Latency
    aws_dimensions: [LoadBalancer, TargetGroup]
    aws_statistics: [Average]
    aws_period: 300
    range_seconds: 600
  - aws_namespace: AWS/ECS
    aws_metric_name: CPUUtilization
    aws_dimensions: [ClusterName, ServiceName]
    aws_statistics: [Average]
    aws_period: 300
    range_seconds: 600
  - aws_namespace: AWS/ECS
    aws_metric_name: MemoryUtilization
    aws_dimensions: [ClusterName, ServiceName]
    aws_statistics: [Average]
    aws_period: 300
    range_seconds: 600
